/// Universal entity primitives for the Life OS data layer.
///
/// Every entity in Life OS shares these base properties.
/// This ensures consistent sync, audit, and soft-delete behavior
/// across all feature domains.
library;

/// The synchronization status of an entity record.
///
/// Used by the sync engine to determine which records
/// need to be pushed to or pulled from Supabase.
enum SyncStatus {
  /// Record is in sync with the remote server.
  synced,

  /// Record has local changes waiting to be pushed.
  pendingPush,

  /// Record was created locally and needs initial push.
  pendingCreate,

  /// Record needs to be pulled from remote.
  pendingPull,

  /// A sync conflict was detected and needs resolution.
  conflict,

  /// Sync failed and will be retried.
  failed,
}

/// Base interface for all Life OS entities.
///
/// Every entity in the system must implement this interface
/// to enable universal sync, audit, and soft-delete operations.
///
/// The properties here are NOT optional — they are required on
/// every table in both Supabase and Drift.
abstract class Entity {
  /// Universally unique identifier.
  ///
  /// Generated by the application (UUID v4), not by the database.
  /// This allows offline creation without server round-trips.
  String get id;

  /// The ID of the user who owns this entity.
  ///
  /// Foreign key to `auth.users.id` / `profiles.id`.
  String get userId;

  /// When this entity was created.
  DateTime get createdAt;

  /// When this entity was last updated.
  DateTime get updatedAt;

  /// When this entity was soft-deleted, if applicable.
  ///
  /// A non-null value means the entity has been soft-deleted.
  /// The actual record is retained for sync and recovery.
  DateTime? get deletedAt;

  /// The current synchronization status of this entity.
  SyncStatus get syncStatus;

  /// A monotonically increasing version number.
  ///
  /// Used for conflict detection during sync.
  /// Incremented on every local mutation.
  int get version;
}

/// Extension on [Entity] for common sync-related checks.
extension EntitySyncX on Entity {
  /// Whether this entity has been soft-deleted.
  bool get isDeleted => deletedAt != null;

  /// Whether this entity needs to be pushed to the server.
  bool get needsPush =>
      syncStatus == SyncStatus.pendingPush ||
      syncStatus == SyncStatus.pendingCreate;

  /// Whether this entity is in a clean, synced state.
  bool get isSynced => syncStatus == SyncStatus.synced;
}
